### PR TITLE
Change instructions in README to use Yarn 

### PR DESCRIPTION
**Pull request by donjar**
I cannot `npm install` and this fixed it so yeah. Is this OK?

### CODE REVIEW

**Comment by indocomsoft** [comment]
Deploy preview for *nushackers* ready!

Built with commit ea7b2a667da6d022eb818751ec058b1984364772

https://deploy-preview-157--nushackers.netlify.com

**Comment by indocomsoft** [comment]
Deploy preview for *nushackers* ready!

Built with commit ea7b2a667da6d022eb818751ec058b1984364772

https://deploy-preview-157--nushackers.netlify.com

**Comment by taneliang** [comment]
@donjar I think you need to run `yarn install` instead, so that you update the yarn.lock file instead of generating a new npm package.lock file

**Comment by donjar** [comment]
@taneliang that did the magic. I updated the README instead

**Pull request merged**
