### PR TITLE
Updated until Recess Week

### PR DESCRIPTION
**Pull request by indocomsoft**

### CODE REVIEW

**Comment by nushackers-org** [comment]
Deploy preview for *nushackers* ready!

Built with commit 17a1a3744c5403ad4f9aa35636ccb20941277af4

https://deploy-preview-134--nushackers.netlify.com

**Comment by indocomsoft** [comment]
I just traced down my commits, turns out I derped my indentation.

**Comment by donjar** [comment]
._. how would that be related to the dependencies errors though

**Comment by indocomsoft** [comment]
The main error is this

```
ERROR 2018/01/29 07:42:14 Error while rendering "section": template: /opt/build/repo/layouts/section/fh.html:8:28: executing "main" at <$date>: can't evaluate field Unix in type *errors.errorString
```

Because it failed to parse the yaml with wrong indentation. The dependency error is just a warning.

**Pull request merged**
