### PR TITLE
change venue for Welcome Tea

### PR DESCRIPTION
**Pull request by donjar**

### CODE REVIEW

**Comment by li-kai** [comment]
Deploy preview ready!

Built with commit b695afce05b6f144070f48459b8aa654c1c477de

https://deploy-preview-77--nushackers.netlify.com

**Comment by advaypal** [comment]
Please change the friday hacks footer text: Remove the old one and replace it with what they want us to put now, as well as change the logo

**Comment by sushinoya** [comment]
@advaypal done in a separate [pull request](https://github.com/nushackers/nushackers-site/pull/79)

**Comment by donjar** [comment]
Obsolete due to #79.

**Pull request closed without merging**
