### PR TITLE
hackerschool:updates

### PR DESCRIPTION
**Pull request by JingYenLoh**

### CODE REVIEW

**Comment by kouyk** [comment]
is it just me or is it weird that for ht, the link to the event specific page is on the date itself?

**Comment by JingYenLoh** [comment]
> is it just me or is it weird that for ht, the link to the event specific page is on the date itself?

Yes, I commented on that in the commit, but I really don't want to deal with it now :')

**Comment by JingYenLoh** [comment]
The CSS for the topic is more specific than the hyperlink, so it doesn't apply the hyperlink styling.
image

A quick workaround is to change the topic to orange, but that makes posts without links orange too, which is unintuitive.
image

There is probably something you can do with hugo templates, but I really don't want to look at their docs now

**Review by kouyk — APPROVED** [review]
LGTM

**Comment by gunbux** [comment]
> > is it just me or is it weird that for ht, the link to the event specific page is on the date itself?
> 
> Yes, I commented on that in the commit, but I really don't want to deal with it now :')

Yea didn't notice that till now actually. I'll try and see if I can fix that when I have the time

**Review by gunbux — APPROVED** [review]

**Pull request merged**
