### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by li-kai**
Just a simple front page redesign. The rest of the site are perfectly functional as they are, I don't see any need to update them.

Now comes with:
- Better focus on our projects
- Fast access to upcoming events (Right now I'm using placeholders)
- New font stack, focusing on legibility.

### CODE REVIEW

**Comment by ngzhian** [comment]
Screens would be nice!

**Comment by li-kai** [comment]
@ngzhian Better than screenshots, deploy previews are available through the details.

https://deploy-preview-58--nushackers.netlify.com/

**Comment by ngzhian** [comment]
Looks good!! Great work :D 

I have 1 small nit, which is to increase the vertical white space between the details in Upcoming Events. The venue feels too close to the title of the first talk, and the first speaker's name is too close to the second talk title.

**Comment by advaypal** [comment]
Thanks @li-kai !
I have a few suggestions/ points for discussion:

1. Shouldn't Friday Hacks be under 'What we do' as well?
2. Not sure how I feel about the horizontal layout vs a vertical one. Also would be helpful to have links to the entire Friday Hacks/Hackerschool schedule

**Comment by donjar** [comment]
Looks great @li-kai! I also have a few points

- is our color scheme orange? I mean I'm OK with it, it's just that I didn't recall NUSHackers being orange haha
- it looks too text heavy somehow? Would adding images help?
- I think the canonical name of Hackerschool is "Hackerschool", not "hacker school"; others can confirm?

**Comment by harishv7** [comment]
Thanks @li-kai! Good stuff! Some suggestions here:
- It's a little text-heavy. Give some "air"/whitespace between text. Ensure the space between different sections follow the same space interval.
- As @donjar said, perhaps adding images will help and make it look more interesting. 
- Space out the 1st and 2nd events for FH
- Not exactly sure about the horizontal / zig-zag layout. I naturally found myself expecting a vertical layout. For example, in Friday Hacks, the events are in ascending order of date from left to right. Under Articles, the left-most side contains the latest article.
- Existing Hackers logo contains orange only on "NUS", are we changing it to full orange?

Great work overall! (Y)

**Comment by li-kai** [comment]
Deploy preview ready!

Built with commit 9beda630a0976924e269882ecbc0f66abb26e3c0

https://deploy-preview-58--nushackers.netlify.com

**Comment by unusep** [comment]
@li-kai let's merge this as soon as you're ready.

**Comment by ngzhian** [comment]
very nice! 👍  ship!

**Comment by ngzhian** [comment]
Oh and we should do a post on our social media once this is pushed :)

**Pull request merged**
