### PR TITLE
Create wiki 

### PR DESCRIPTION
**Pull request by Devanshshah1309**

### CODE REVIEW

**Comment by Devanshshah1309** [comment]
> Under Programming languages, we can include the Practical Functional Programming/Intro to Elixir too?

Oh yeah i forgot about that, I'll add that too

**Comment by zwliew** [comment]
Hey, let's get this moving as a start. I reckon we should rename "Wiki" to "Archive" to avoid confusing it with https://wiki.nushackers.org/

**Comment by Devanshshah1309** [comment]
Actually, I remember @francisyzy and I having this discussion too (about why we didn't use "Archive") -- because the past FH talks are also listed under the `/archive` route.

**Comment by zwliew** [comment]
> Actually, I remember @francisyzy and I having this discussion too (about why we didn't use "Archive") -- because the past FH talks are also listed under the `/archive` route.
> 
> How about we rename the past FH talks to "/talks", and use "/archive" for this?

Yup that sounds good!

**Review by zwliew — APPROVED** [review]
I renamed archive -> articles and wiki -> archive. Does this look good to you?

**Comment by Devanshshah1309** [comment]
> I renamed archive -> articles and wiki -> archive. Does this look good to you?

Yup, let's merge this.

**Pull request merged**
