### PR TITLE
Add RSS

### LINKED ISSUE #23: RSS feed for all of our events
Because not everyone is on FB/Twitter.

### PR DESCRIPTION
**Pull request by donjar**
FIxes #23

### CODE REVIEW

**Comment by indocomsoft** [comment]
Deploy preview for *nushackers* ready!

Built with commit 1e7c71e9ce2e9df05739ef0f61c8b85fdea78f0f

https://deploy-preview-158--nushackers.netlify.com

**Comment by donjar** [comment]
@indocomsoft you might want to revert Netlify haha

**Comment by indocomsoft** [comment]
Deploy preview for *nushackers* ready!

Built with commit 1e7c71e9ce2e9df05739ef0f61c8b85fdea78f0f

https://deploy-preview-158--nushackers.netlify.com

**Comment by indocomsoft** [comment]
Haha yeah I'll deal with that later

**Pull request merged**
