### PR TITLE
Welcome tea 2017

### PR DESCRIPTION
**Pull request by sushinoya**
Screenshot:
screen shot 2017-08-17 at 12 04 41 am

### CODE REVIEW

**Comment by li-kai** [comment]
Deploy preview ready!

Built with commit 02c688b5f844d238f9a820ca47318a52b68593d5

https://deploy-preview-79--nushackers.netlify.com

**Comment by advaypal** [comment]
You can remove the last line about having ideas.

**Comment by li-kai** [comment]
Please compress the image. 64kb is way too big.

**Comment by donjar** [comment]
@li-kai is 17KB ok?

**Pull request merged**
