### PR TITLE
Improve post styles

### PR DESCRIPTION
**Pull request by yangshun**
For posts that do not have a previous or next, the post pagination will be messed up. This PR fixes it, along with some minor styling issues, such as at the bottom of this [page](http://www.nushackers.org/2017/09/17/digest-preparing-for-a-coding-interview/):

screen shot 2017-10-07 at 11 12 26 pm

### CODE REVIEW

**Comment by li-kai** [comment]
Deploy preview ready!

Built with commit fe5f9c7e7e61362e3894aaac5b38178dcca26574

https://deploy-preview-108--nushackers.netlify.com

**Comment by advaypal** [comment]
Thanks @yangshun! Unfortunately I think one of the style changes you made has caused some unintended changes..

Before:
screen shot 2017-10-07 at 11 28 23 pm

After:

screen shot 2017-10-07 at 11 25 35 pm

**Comment by yangshun** [comment]
I've removed `bootstrap/type` as the site is not currently suited for that typography. Using `bootstrap/reboot` without `bootstrap/type` and your own custom styling is not a good idea because all headings will have the same font size unless specified otherwise. But it's a bigger change that should be done in a separate PR, will remove it.

cc @li-kai

**Comment by advaypal** [comment]
Ah, I see. Thanks so much!

**Pull request merged**
